version: '3' 
services:

  spark-enem:
    image: fjardim/jupyter-spark
    hostname: jupyter-spark
    container_name: spark-enem
    command: notebook
    env_file:
      - ./env/jupyter.env
    ports:
      - 8889:8889
      - 4040:4040
      - 4041:4041
      - 4042:4042
      - 4043:4043
    volumes:
       - ./src:/mnt/notebooks/
    environment:
       SPARK_MASTER: local[*]
       JUPYTER_PORT: 8889
    deploy:
      resources:
        limits:
          memory: 1g
